apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}
